### PR TITLE
initial fastlane structures

### PR DESCRIPTION
**Pull request by IzzySoft**
…for [your MR with F-Droid](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7353) (details there).

### CODE REVIEW

**Comment by IzzySoft** [comment]
@desyncr any chance this will be processed? I'm about cleaning up my Github account before this year's end and drop "old forks" I don't plan to maintain – and once I drop the fork of your app, this PR will go "stale" as the source is gone.

**Comment by IzzySoft** [comment]
Anyone here? Your request at F-Droid is still waiting for this to be merged.

**Comment by desyncr** [comment]
Sorry for the delay. Had a pause from coding.

**Comment by IzzySoft** [comment]
All fine! What's due is due, and if a break is needed a break is due :wink: Thanks! I see you've also tagged it already, so we can give that RFP a kick now.

PS: to build on this, be welcome to use my [Fastlane Cheat Sheet](https://gitlab.com/snippets/1895688). Especially screenshots would be very welcome.

**Comment by desyncr** [comment]
I'll add the screenshots in a following PR. Thanks for the push :smile:

**Pull request merged**
